[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PartialFunctions = "570af359-4316-4cb7-8c74-252c00c2016b"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
